### ISSUE TITLE
<Functionality>: Product page segment

### ISSUE THREAD

**Issue by Kawaiibuta** [phuochungus/api.precious.com#3]
![image](https://github.com/phuochungus/api.precious.com/assets/163984214/e065a9ee-ffe2-4f73-869e-7f90b2508166)
1. Add a start index and end index param (?start=<number>).
2. Add a quantity number (?quantity= <number>)
The logic flow will be:
1. The controller call API to get A products from index 0;(?quantity=A&start=0)
2. The server return A products.
3. The user has swiped through A products.
4. The controller call API to get B products (different from A products) starting from index A.(?quantity=B&start=A)
5. Repeat from 2.
The downfall of this approach could be the select * query is called too much time and reduce the response time of the API. To work around this downfall, please consider using a Table to save list of product id and index number.
The workflow will be:
After receive call from (1), server select all of the products and shuffle. Then, the server save a list of Product's id with user id and number that show how many item have been sent to user, i.e {list: [1,3,5,2,....], user: <userID>, read: A}.
After receive call API (4) the server return item from the list with startIndex is <read> and endIndex is <read> + B.
This is only a possible work around, if you have any better solution to this problem, Please using it and inform me in detail.

**Comment by phuochungus** [comment]
@Kawaiibuta  Done
