### ISSUE TITLE
<Functionality>: Product type and filter product by type

### ISSUE THREAD

**Issue by Kawaiibuta** [phuochungus/api.precious.com#4]
![func](https://github.com/phuochungus/api.precious.com/assets/163984214/1b185a97-24d1-40c9-b12b-398286fe4cce)
Add a type attribute to Product class to filter products and add getByType API to retrieve all product that have a specified type.

**Comment by phuochungus** [comment]
@Kawaiibuta type = category? or else?

**Comment by phuochungus** [comment]
Done
