### ISSUE TITLE
<Issue>: Call getAll with quantity > remaining product

### ISSUE THREAD

**Issue by Kawaiibuta** [phuochungus/api.precious.com#5]
![image](https://github.com/phuochungus/api.precious.com/assets/163984214/a8cd7017-5f3d-430c-949a-3773f41c69f5)
Call getAll product API with quantity param > remaining product result in emtpy list => NOT IDEAL
Expected workflow: if the remaining product < quantity => return all of the remaining product.

**Comment by phuochungus** [comment]
@Kawaiibuta 
![image](https://github.com/phuochungus/api.precious.com/assets/111514441/5902aa04-9fe2-4905-a37f-982c2a7849a4)

**Comment by phuochungus** [comment]
Done
